[Profile]コードのコンポーネント化とprofile欄から自分のIDgetをできるようにした
Shuta-syd/42-ft_transcendence pull request #162
Opened 2023-03-28 15:19 UTC by Jack-in-42Tokyo

## やったこと
1.Profile関連の実装に関してファイルに分割したり、コンポーネント化することで可読性を上げた(Profile.tsx)
2.指紋のiconにタッチするとuserのidを取れるようになった。(clipboardにコピーされる)

- 次やるべきこと(新たなissue)があれば記載
friend申請(現状はフレンド申請をしても、相手に通知が届いたりはしないので、その点を修正する必要がある)

- どのような動作確認を行ったのか？　結果はどうか？
Profile欄に行ってみて、指紋のiconがあるのでそこを押すとうまくコピーできるので、相手のフレンド申請欄に入れてみてください。友達として登録されるはず。
コンポーネントしたのも見たければ、profile.tsx(frontend)見にいけば見れます！

about : #155 

see also : #155 

close #155

2023-03-28 15:46 UTC, kny-i approved these changes
GOOD work

2023-03-29 14:57 UTC, public-jun requested changes
最新のmain取り込んで、コンフリクト修正しといてほしい！

2023-03-29 15:05 UTC, public-jun reviewed
フレンドIDを送信したら、フレンドID入力欄を空にして欲しい

2023-03-31 04:28 UTC, Jack-in-42Tokyo commented
merge間違えたので修正します

2023-03-31 08:03 UTC, Jack-in-42Tokyo commented
buttonを押した時に消せたと持ったけどまだ副作用が取れてないので、mainへのmergeはお待ちください

2023-03-31 14:04 UTC, public-jun approved these changes
OK!

2023-03-31 14:05 UTC, merged