[Profile] profile ui update
Shuta-syd/42-ft_transcendence pull request #175
Opened 2023-03-29 21:50 UTC by Jack-in-42Tokyo

## やったこと
profileのデザインとカラーを変更

- 次やるべきこと(新たなissue)があれば記載
機能面での不備を修正していく

## 動作確認
Profile欄のUIをチェックしてください
中央揃えだといまいちだと思ったので、一旦現状デザインにしました。もし微妙だと思ったらcenter揃えに後で修正

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

## issues

about : #164

2023-03-29 22:15 UTC, kny-i approved these changes
Okay

2023-03-31 15:53 UTC, public-jun requested changes
最新のmainブランチが取り込まれていないと思うから、確認してほしい！
フロントが前のログイン画面になっている

2023-03-31 23:16 UTC, Jack-in-42Tokyo commented
> ![localhost_3000_user (2)](https://user-images.githubusercontent.com/60804160/229171081-0564df0f-38a5-45c4-bc87-2055e9d742a8.png) 画面に収まっていない要素があるから、（画像アップロードボタン、カメラアイコン、下部のゲーム履歴部分など）レスポンシブだと最高。 pdfの見た目にするのは、これからという認識でおっけい？

色々profileのデザインで既存のものを見てみたんですが、実はかっこよさを左右してるのが背景画像なんじゃないかって仮説の元、yukiに背景画像入れてもらいました！ただ仮決定という認識で問題ないです！

それとpdfにどこまで沿うべきかということに関しては真ん中に全部寄せれば、端に寄せた時にフレキシブルじゃなくなってしまうという問題は改善できるのですが、かなり微妙なUIになってしまうのがyukiと話した上での結論だったので、現状そうしているんですが、一旦修正して、また微妙なんじゃないかと思ったら再検討させてください！

2023-03-31 23:16 UTC, Jack-in-42Tokyo commented
mainを取り込んだ上で一度pdfにできるだけ合わせた仕様に変更します

2023-04-01 00:12 UTC, Jack-in-42Tokyo commented
@public-jun 
flexibleかつpdfに沿った仕様に(まだ機能的にもできないので厳密にではないが)変更してみたので、reviewお願いします！

[左に寄せてるver]
![Screen Shot 2023-04-01 at 9 10 35](https://user-images.githubusercontent.com/94432194/229255094-a7dac4c7-964d-45b7-af2e-57794b0dbef5.png)

[通常ver]
![Screen Shot 2023-04-01 at 9 11 36](https://user-images.githubusercontent.com/94432194/229255137-85d1d2e7-ee9a-4db6-bef2-2679fe440f6c.png)

2023-04-01 04:02 UTC, kny-i commented
@public-jun file change reqがある場合にはmergeできないんですかね？
pdfと同じような配置にしたのでokayお願いします！

2023-04-01 16:03 UTC, public-jun reviewed
ごめんお待たせしました！
ありがとう！修正確認しました！レイアウトはGoodです！
俺が言いたかったのは背景画像とかではなくてボタン要素が横のNavbarにはみ出た点だったから、好みの画像とかあるなら全然使ってくれても良いと思うよ！

![localhost_3000_user (4)](https://user-images.githubusercontent.com/60804160/229301284-f9e81cc8-767d-40f8-8544-b01359c270f3.png)

一点気になったのは画面の横幅を小さくした際（具体的には約1220px以下）にしたときにprofile要素が全部下に配置されてしまうのは何故かわかる？

できたらchatみたいに画面幅を小さく（具体的にはディスプレイの半分程度、レビュー時は2窓で画面分割されて行われる可能性が高いから）した時でも出来るだけpdfに沿って配置は可能かな？
![localhost_3000_user (5)](https://user-images.githubusercontent.com/60804160/229301445-c9734d9a-dc23-44e7-a44e-5a1788bad9c4.png)

2023-04-02 02:03 UTC, Jack-in-42Tokyo commented
> ごめんお待たせしました！ ありがとう！修正確認しました！レイアウトはGoodです！ 俺が言いたかったのは背景画像とかではなくてボタン要素が横のNavbarにはみ出た点だったから、好みの画像とかあるなら全然使ってくれても良いと思うよ！
> 
> ![localhost_3000_user (4)](https://user-images.githubusercontent.com/60804160/229301284-f9e81cc8-767d-40f8-8544-b01359c270f3.png)
> 
> 一点気になったのは画面の横幅を小さくした際（具体的には約1220px以下）にしたときにprofile要素が全部下に配置されてしまうのは何故かわかる？
> 
> できたらchatみたいに画面幅を小さく（具体的にはディスプレイの半分程度、レビュー時は2窓で画面分割されて行われる可能性が高いから）した時でも出来るだけpdfに沿って配置は可能かな？ ![localhost_3000_user (5)](https://user-images.githubusercontent.com/60804160/229301445-c9734d9a-dc23-44e7-a44e-5a1788bad9c4.png)

これ修正しようと粘ってみたんですが、難しかったので、今日のMTGでオグちゃんに聞こうと思います！
なので一旦これはgameも含めて別issueにしておきます！

2023-04-02 02:24 UTC, public-jun commented
> > ごめんお待たせしました！ ありがとう！修正確認しました！レイアウトはGoodです！ 俺が言いたかったのは背景画像とかではなくてボタン要素が横のNavbarにはみ出た点だったから、好みの画像とかあるなら全然使ってくれても良いと思うよ！
> > ![localhost_3000_user (4)](https://user-images.githubusercontent.com/60804160/229301284-f9e81cc8-767d-40f8-8544-b01359c270f3.png)
> > 一点気になったのは画面の横幅を小さくした際（具体的には約1220px以下）にしたときにprofile要素が全部下に配置されてしまうのは何故かわかる？
> > できたらchatみたいに画面幅を小さく（具体的にはディスプレイの半分程度、レビュー時は2窓で画面分割されて行われる可能性が高いから）した時でも出来るだけpdfに沿って配置は可能かな？ ![localhost_3000_user (5)](https://user-images.githubusercontent.com/60804160/229301445-c9734d9a-dc23-44e7-a44e-5a1788bad9c4.png)
> 
> これ修正しようと粘ってみたんですが、難しかったので、今日のMTGでオグちゃんに聞こうと思います！ なので一旦これはgameも含めて別issueにしておきます！

おっけい！ありがとう！

2023-04-02 02:24 UTC, public-jun approved these changes
OK!

2023-04-02 02:26 UTC, merged