Chatのリファクタリング（ローディング処理、参加者リストの仕様変更）
Shuta-syd/42-ft_transcendence pull request #212
Opened 2023-04-04 09:46 UTC by Shuta-syd

## やったこと

- このプルリクで何をしたのか？
- 機能追加の背景や動機は？

## やらないこと

- 次やるべきこと(新たなissue)があれば記載

## 動作確認

- どのような動作確認を行ったのか？　結果はどうか？

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

## issues

about : #0

see also : #0

close #0

2023-04-05 10:55 UTC, public-jun approved these changes
OK!

2023-04-06 06:40 UTC, kny-i commented
> frontend  | ERROR in ./node_modules/socket.io-client/build/esm/index.js
frontend  | Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):
frontend  | Error: ENOENT: no such file or directory, open '/frontend/node_modules/socket.io-client/build/esm/index.js'
frontend  | 
frontend  | webpack compiled with 51 errors and 1 warning
frontend  | ERROR in src/components/auth/TwoFactorDialog.tsx:4:27
frontend  | TS2307: Cannot find module 'next-qrcode' or its corresponding type declarations.
frontend  |     2 | import { Box, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, InputAdornment, Stack, TextField, Typography } from "@mui/material";
frontend  |     3 | import axios from "axios";
frontend  |   > 4 | import { useQRCode } from "next-qrcode";
frontend  |       |                           ^^^^^^^^^^^^^
frontend  |     5 | import ClearIcon from '@mui/icons-material/Clear';
frontend  |     6 | import React, { useEffect, useState } from "react";
frontend  |     7 | import { Navigate } from "react-router-dom";
frontend  | 

こんな感じでmodule の buildに失敗しちゃったな

2023-04-06 06:40 UTC, kny-i commented
@Shuta-syd

2023-04-06 06:50 UTC, Shuta-syd commented
npm ciして

2023-04-06 07:49 UTC, kny-i commented
動いた！
現状user Idで遷移してるけど、結局user/nameになったからそっちに変更しないといけないね
それ以外はOKAY

2023-04-06 07:50 UTC, kny-i requested changes
user/id
を
user/nameにする。

2023-04-06 07:50 UTC, Shuta-syd commented
> user/id を user/nameにする。

これは別イシューだから今回のプルリクでは大丈夫

2023-04-06 07:53 UTC, Shuta-syd commented
やっぱなおすわ

2023-04-07 08:15 UTC, kny-i approved these changes
good!

2023-04-07 08:15 UTC, merged