【Chat】ブロックしているユーザのメッセージを表示しない仕様に変更
Shuta-syd/42-ft_transcendence pull request #249
Opened 2023-04-11 09:06 UTC by Shuta-syd

## やったこと
- ブロックしているユーザのメッセージを表示しない仕様に変更
- Channel編集画面の更新
- DMの相手がLeaveした時のエラー解消

## 次回アクション
- #215 
- #205

## 動作確認
```
複数ユーザを作成
チャンネルを作成して所属して会話する
特定のユーザをポストマンでブロックする
ブロックしたユーザのメッセージが表示されていないか確認
```

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

## issues

about : #104 

see also : #224 

close #104 #224

2023-04-12 00:14 UTC, Shuta-syd commented
レビューお願いします

2023-04-12 00:22 UTC, Shuta-syd commented
https://user-images.githubusercontent.com/98635404/231315903-dd298594-ffc7-475f-80f6-0e9f42623a0c.mov

texがchanをブロックしている状況

2023-04-12 07:20 UTC, Jack-in-42Tokyo approved these changes
GOOD WORK!

2023-04-12 14:39 UTC, public-jun requested changes
ソケットが繋がってるから、リアルタイムの発言が表示されてしまってた！
リロードすれば、発言は消えてる。


user1がuser2をブロックしている状態


https://user-images.githubusercontent.com/60804160/231492783-ff5e5b04-0faf-4146-8231-84aa62dea3e4.mov

2023-04-13 02:09 UTC, Shuta-syd commented
> 

たしかに！発言の部分のフィルタリングは実装忘れてました！やります！

2023-04-13 02:39 UTC, Shuta-syd commented
修正しました

2023-04-13 14:10 UTC, merged