[Profile]倍率の修正とbutton push後にカードが消えるように修正
Shuta-syd/42-ft_transcendence pull request #250
Opened 2023-04-11 09:53 UTC by NIhkCK

## やったこと
1.accept( or decline)buttonを押したときにcard(通知を出してた枠)が消えるようにして、消え方がスムーズになるように変更した
2.Profileの画面がこれまで自分が無意識で75%にしていたためみんなとの見え方に差があったのを修正しました
(想定倍率が100%)になったので、これまでみたいに半分の画面にした時に下にprofileが移ってしまうようなbugも解消されたと思います

## 動作確認
1.に関しては以前より自分とprofile、自分以外のprofileが全体的に小さくなっていれば問題ありません。
また片方に寄せても下にprofileが移動したりしないことも確認していただけると助かります。
2に関しては、ユーザーを二人作って、以前の通りフレンド申請ボタンを片方のユーザーで申請後、自分のprofileで申請をacceptもしくはdeclineしてください。この時にボタンを押した直後にカード(material uiのcard、通知の大枠を指しています)が消えていれば問題ありません。

## issues

about : #238 #248 

close #238 #248

2023-04-12 04:37 UTC, kny-i commented
backエンド側の問題だけど、すでにfriendになってる相手にはfriend Reqはおくれないようにした方が良さそうね
それ以外okay!

2023-04-12 04:37 UTC, kny-i approved these changes
GJ

2023-04-12 04:39 UTC, Jack-in-42Tokyo commented
> backエンド側の問題だけど、すでにfriendになってる相手にはfriend Reqはおくれないようにした方が良さそうね
> 
> それ以外okay!

ありがとう！
issue立ててあるので、そこで解消します😃

2023-04-12 14:59 UTC, public-jun requested changes
accept(decline)素晴らしい！めちゃくちゃいい出来:+1:

プロフィールについてやけど分割したらまだ下になってた
画面が小さくなると、見切れても良いから上に要素を配置してほしい

<img width="723" alt="スクリーンショット 2023-04-12 23 55 58" src="https://user-images.githubusercontent.com/60804160/231497641-cc4547fd-8303-4cf5-991f-9871571d9e9c.png">

2023-04-13 03:37 UTC, Jack-in-42Tokyo commented
> accept(decline)素晴らしい！めちゃくちゃいい出来👍
> 
> プロフィールについてやけど分割したらまだ下になってた 画面が小さくなると、見切れても良いから上に要素を配置してほしい
> 
> <img alt="スクリーンショット 2023-04-12 23 55 58" width="723" src="https://user-images.githubusercontent.com/60804160/231497641-cc4547fd-8303-4cf5-991f-9871571d9e9c.png">

もう少し小さくしてみます！
> 見切れても良いから上に要素を配置してほしい

これについてはmaterial ui使ってるとnavbarとprofileの要素が衝突をして下に来ちゃうんですよね。。
一旦profileをもう少し小さくして解消してみようと思います！

2023-04-13 04:59 UTC, Jack-in-42Tokyo commented
<img width="1696" alt="Screen Shot 2023-04-13 at 13 58 00" src="https://user-images.githubusercontent.com/94432194/231657619-eaba33f2-ec3d-4eb4-91a0-c7ceac982fd4.png">

@public-jun 
これbこれ僕の方だと100%で確認しても問題なさそうなんですよね。。

2023-04-13 05:05 UTC, Jack-in-42Tokyo commented
@public-jun 
#255のpull requestの方だと今よりもさらに小さくしてるんですが、このサイズだとどうなりますか？？
もし255の方のサイズで問題がなければ、一旦このpull requestをapproveしてもらって、255をmergeすれば、問題なくなると思います！
もしそれでもまだ問題があった場合にはボイチャで画面見せていただきたいです！

2023-04-13 05:12 UTC, Jack-in-42Tokyo commented
https://user-images.githubusercontent.com/94432194/231659778-c7cb0d33-9da5-4977-8b60-f07523d9396d.mov

参考までに#255のpull reqではこのくらいの感じになっています！

2023-04-13 05:26 UTC, public-jun commented
> 参考までに#255のpull reqではこのくらいの感じになっています！

多分俺のmacbookは13インチ使ってるから、ハルくんのより小さいからやと思う！
半分にしたら、750pxくらい！

2023-04-13 05:28 UTC, Jack-in-42Tokyo commented
> > 参考までに#255のpull reqではこのくらいの感じになっています！
> 
> 多分俺のmacbookは13インチ使ってるから、ハルくんのより小さいからやと思う！ 半分にしたら、750pxくらい！

pull request255の方のサイズだとどうですか？？

2023-04-13 05:29 UTC, public-jun commented
> > > 参考までに#255のpull reqではこのくらいの感じになっています！
> > 
> > 
> > 多分俺のmacbookは13インチ使ってるから、ハルくんのより小さいからやと思う！ 半分にしたら、750pxくらい！
> 
> pull request255の方のサイズだとどうですか？？

おけ！今晩255でまた確認してみる！

2023-04-13 05:31 UTC, Jack-in-42Tokyo commented
よろしくお願いします！

2023-04-13 10:58 UTC, public-jun approved these changes
OK!

2023-04-13 10:58 UTC, merged