intra名が被ってしまった場合またはすでに同様のユーザネームが存在する場合のバグ解消
Shuta-syd/42-ft_transcendence pull request #256
Opened 2023-04-12 08:19 UTC by Shuta-syd

## やったこと
- intra名が被ってしまった場合またはすでに同様のユーザネームが存在する場合のバグ解消
- intra名をuuidv4()で被らないように登録後、編集してもらうスタイルに変更
- emailアドレスも通常ログインと被る可能性があるためsha256でハッシュ化して登録（通常ログインもできる）

## 次回アクション
- #205 
- Gameの整備

## 動作確認
```
42ログインをしてusername編集画面がでるか確認
```

## issues

about : #215 

close #215

2023-04-12 08:21 UTC, Shuta-syd commented
Profileになぜか表示されないバグがあるけどこれは42ログインに限った話だからProfile側に何か問題があるかも

2023-04-12 08:21 UTC, Shuta-syd commented
通常ログインはProfileバグは起きません

2023-04-12 15:38 UTC, public-jun commented
> Profileになぜか表示されないバグがあるけどこれは42ログインに限った話だからProfile側に何か問題があるかも

下に表示されるやつ？

2023-04-12 15:39 UTC, public-jun approved these changes
OK！！

2023-04-12 21:31 UTC, kny-i commented
「すでに同じ名前の人が存在するから、別の名前を登録してください。」っていう旨をclientに伝えた方が良さそう。
42login したのになんでuser nameをもう一度入力するんだろうならないように！
それ以外okay

2023-04-12 21:32 UTC, kny-i requested changes
同じ名前がすでに存在するので、別の名前を登録してください。
っていう旨をuserに知らせる機能の実装。

2023-04-13 01:59 UTC, Shuta-syd commented
> 同じ名前がすでに存在するので、別の名前を登録してください。 っていう旨をuserに知らせる機能の実装。

この仕様実装してるんだけど機能してなかった？確認して欲しい

2023-04-13 02:01 UTC, kny-i commented
了解！
みてみる！
@Shuta-syd

2023-04-13 05:20 UTC, Jack-in-42Tokyo commented
> Profileになぜか表示されないバグがあるけどこれは42ログインに限った話だからProfile側に何か問題があるかも

少なくともこれまでのprofileで確認してみた感じ表示されないということはなさそうなんだけど、現状のmainブランチのprofileだとjunyaくんが言ってるように下の方に表示されてしまうということは起きてるかもしれない。

ただ#255でサイズを大幅に小さくして、そういう問題も無くなっていると思う

2023-04-17 11:09 UTC, kny-i commented
これ、42authからトラセンに戻ってくる時に名前の変更を求められると思うんだけど、その時にあなたのnameが被っていたので別のnameに変更してください。的な文章を出すことってできる？

2023-04-17 11:12 UTC, kny-i approved these changes
GOOD

2023-04-17 11:12 UTC, merged