Game matchig/issue257
Shuta-syd/42-ft_transcendence pull request #258
Opened 2023-04-12 23:38 UTC by kny-i

## やったこと

random match systemの構築

## やらないこと
マッチングの部分以外のgame

- 次やるべきこと(新たなissue)があれば記載

## 動作確認
userを二人作成。
各々のuserでhttp://localhost:3000/pongにアクセスする。
random matchが成立してroomIdが付与されるのを確認する。

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

## issues

about : #0

see also : #0

close #0

2023-04-12 23:40 UTC, kny-i commented
https://user-images.githubusercontent.com/88308445/231609110-7981806d-c51f-4eec-8c14-9bec90a6c1d6.mov

2023-04-13 00:03 UTC, kny-i commented
issue番号間違えてますね。
気にしないで！

2023-04-13 02:04 UTC, Shuta-syd requested changes
余計なものが入っちゃってるからそこらへんの整理お願いします！

コードとかもできるだけ俺も追ってくからがんばろ！

2023-04-13 02:04 UTC, Shuta-syd commented on backend/.eslintrc.js
pluginとかはすべて今までのものを引き継ぎたいからこの辺の変更は戻して欲しい

2023-04-13 02:04 UTC, Shuta-syd commented on backend/.prettierrc
これも同じで前のもを使用したい

2023-04-13 02:04 UTC, Shuta-syd commented on backend/package.json
バージョンも前のままがいいかな。無闇に更新すると依存関係が壊れてbuildできなくなるから

2023-04-13 02:04 UTC, Shuta-syd commented on frontend/package.json
このも同様に変更を取り消して欲しい

2023-04-13 02:04 UTC, Shuta-syd commented on package.json
このPackage.jsonはプロジェクトに関係ないからけして欲しい

2023-04-13 02:04 UTC, Shuta-syd commented on package-lock.json
これも同様にけして欲しい

2023-04-13 02:09 UTC, kny-i commented on backend/.eslintrc.js
おっけ！

2023-04-13 21:14 UTC, kny-i commented
@Shuta-syd チェックお願い

2023-04-15 07:30 UTC, public-jun approved these changes
OK!

2023-04-18 14:33 UTC, merged