[Profile]block周りの機能を実装
Shuta-syd/42-ft_transcendence pull request #267
Opened 2023-04-15 13:24 UTC by Jack-in-42Tokyo

## やったこと
Blockボタンを実装しました

## 動作確認
- どのような動作確認を行ったのか？　結果はどうか？

Blockボタンを実装したので、prismaを確認しながらblockをしたときに、block listが変更されていることを確認してみてください。
またblockしたユーザーからのフレンド申請は受付できない仕様となっています。
unblockに関してもblockしたユーザーは可能なので、試してみてください。

## issues

about : #165 
close #165

2023-04-18 10:58 UTC, kny-i commented
block してから unblock すると、その後にblock するためのボタンが出てこない気がする！

2023-04-18 10:58 UTC, kny-i commented
<img width="1257" alt="Screenshot 2023-04-18 at 7 58 31 PM" src="https://user-images.githubusercontent.com/88308445/232757158-a9448b49-73e2-45b4-8aff-1fa4ab9a1f03.png">

2023-04-18 10:59 UTC, kny-i commented
上の画像でUNBlockしても再度blockボタンを押すのが難しそう

2023-04-20 11:49 UTC, public-jun commented
block -> unblockが正常に表示されるかチェックする

2023-04-20 13:58 UTC, public-jun requested changes
ブロック自体はできてたけど、いくつか不具合報告するね

- `UNFRIEND`と`BLOCK`ボタンは共存しないと思ってたけど、違うかな？
![スクリーンショット 2023-04-20 22 31 27](https://user-images.githubusercontent.com/60804160/233382143-dff41e5d-8bf9-4244-9163-e5c6b76159c6.png)

- `UNFRIEND`した後もfriend状態になっていた

https://user-images.githubusercontent.com/60804160/233388784-b393030e-8aa8-4bda-b6a0-dfc48d626175.mov



- 上の状態でブロックを実施すると、フレンドかつブロック状態になった。

- [こんちゃんの指摘事項](https://github.com/Shuta-syd/42-ft_transcendence/pull/267#issuecomment-1512875144)
俺の環境でも再度blockの表示は無かった。
DB見ると`UNBLOCK`がそもそもできて無かった！
`block->unblock(ここが失敗している)->block(表示されない)`
DBで直接ブロック解除すると正常にblockボタンが再表示されていたので、`UNBLOCK`ボタンに原因があると思う

2023-04-20 16:22 UTC, Jack-in-42Tokyo commented
@public-jun 
問題確認できたので、状態管理3つに関してはもう一度修正してみます。

2023-04-20 16:58 UTC, Jack-in-42Tokyo commented
mainをmergeしたタイミングでunfriendができなくなっていたので、おかしくなっている可能性のある部分をチェックしてみます

2023-04-20 17:08 UTC, Jack-in-42Tokyo commented
@public-jun main.tsの22行目が問題だったぽいので解消しました。
またjunyaくんが指摘してくれた問題点に関しては、修正完了しました！

2023-04-21 05:06 UTC, public-jun commented
> @public-jun main.tsの22行目が問題だったぽいので解消しました。
> 
> またjunyaくんが指摘してくれた問題点に関しては、修正完了しました！

ありがとう！
指摘した点について、また見ときます！

2023-04-22 08:04 UTC, public-jun approved these changes
Good!
修正バッチリできてました！

2023-04-22 12:27 UTC, kny-i commented
okay!

2023-04-22 12:28 UTC, kny-i approved these changes

2023-04-22 12:28 UTC, merged