Game match edit
Shuta-syd/42-ft_transcendence pull request #375
Opened 2023-05-06 04:18 UTC by kny-i

## やったこと

match serviceにroomIdを取得する処理を追加した。
それに伴いMatchDtoの中から、roomId を削除した。

2023-05-06 10:17 UTC, Shuta-syd requested changes
正常終了した場合Matchに成績が生成されず、アチーブメントに反映されていない。（Matchデータベース作られていない）
![Screenshot 2023-05-06 at 19 16 36](https://user-images.githubusercontent.com/98635404/236618232-d3322cd6-eb51-4724-b954-9acb805fd36c.png)

2023-05-06 10:22 UTC, Shuta-syd commented
フロントのコンソール表示も削除よろしく

2023-05-06 14:48 UTC, public-jun commented
> 

Profile上でのマッチの表示がおかしいのは俺のPRで治ってるはずやから、データベースが正しくできているかを確かめてほしい。
これはデータベースも正しくできてなかったのかな？

2023-05-06 14:49 UTC, kny-i commented
@public-jun 表示おかしかったですか？

2023-05-07 00:10 UTC, public-jun commented
このPRは見なくてよし

2023-05-07 05:53 UTC, closed without merging